In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
x = np.array(list(range(3,33)) + [3.2,6.2])
x = x[:,np.newaxis]


In [21]:
test = np.array([i/10 for i in range(400)])
test = test[:,np.newaxis]
np.sum([[0, 1], [0, 5]], axis=1)
test

array([[  0. ],
       [  0.1],
       [  0.2],
       [  0.3],
       [  0.4],
       [  0.5],
       [  0.6],
       [  0.7],
       [  0.8],
       [  0.9],
       [  1. ],
       [  1.1],
       [  1.2],
       [  1.3],
       [  1.4],
       [  1.5],
       [  1.6],
       [  1.7],
       [  1.8],
       [  1.9],
       [  2. ],
       [  2.1],
       [  2.2],
       [  2.3],
       [  2.4],
       [  2.5],
       [  2.6],
       [  2.7],
       [  2.8],
       [  2.9],
       [  3. ],
       [  3.1],
       [  3.2],
       [  3.3],
       [  3.4],
       [  3.5],
       [  3.6],
       [  3.7],
       [  3.8],
       [  3.9],
       [  4. ],
       [  4.1],
       [  4.2],
       [  4.3],
       [  4.4],
       [  4.5],
       [  4.6],
       [  4.7],
       [  4.8],
       [  4.9],
       [  5. ],
       [  5.1],
       [  5.2],
       [  5.3],
       [  5.4],
       [  5.5],
       [  5.6],
       [  5.7],
       [  5.8],
       [  5.9],
       [  6. ],
       [  6.1],
       [

In [15]:
np.sum([[0, 1], [0, 5]], axis=0)

array([0, 6])

In [29]:
x = np.array([[3],[4],[5]])
y = np.array([[0],[0.1],[0.2]])
for i in range(len(y)):
    wts = np.sum(x - y[i],axis=1)
np.diag(wts)

array([[ 2.8,  0. ,  0. ],
       [ 0. ,  3.8,  0. ],
       [ 0. ,  0. ,  4.8]])

In [ ]:
[ 3.  4.  5.]
[ 2.9  3.9  4.9]
[ 2.8  3.8  4.8]

In [ ]:
x_train = np.array()
x_test
y_test